num1=eval(input("Enter First Number : "))
num2=eval(input("Enter Second Number : "))
print("Addition is : ", num1+num2)
print("Subtraction : ", num1-num2)
print("Multiplication : ", num1*num2)
print("Division : ", num1/num2)
print("Modulus  : ", num1%num2)
print("Exponent : ", num1**num2)
print("Floor Division : ", num1//num2)
