a=eval(input("Enter First Number : "))
b=eval(input("Enter Second Number :"))
print("Greater than : ", a>b)
print(" Less Than   : ", a<b)
print("Greater than or equal too : ", a>=b)
print("Less than or equal too : ", a<=b)
print("Equal too : ",a==b)
print("Not Equal to : ",a!=b)
